### PR TITLE
adds: [logger] raw DNS response

### PR DESCRIPTION
**Pull request by gallypette**
This PR adds the ability to have the base64 encoded payload in logger's  text-format output.

### CODE REVIEW

**Comment by dmachard** [comment]
Thank you for this pull request.
Can you update the following [doc]( https://github.com/dmachard/go-dns-collector/blob/main/doc/configuration.md#custom-text-format) with this new directive ?

**Comment by gallypette** [comment]
done

**Review by dmachard — CHANGES_REQUESTED** [review]
Can you remove the response_payload for the JSON output ? 
`Payload []byte `json:"response_payload" msgpack:"-"`
`
The JSON message size will increased with that. I prefer to keep a small size by default.

If you want that perhaps it will be better to add a new  transform  witch add a new field in the payload in base64
https://github.com/dmachard/go-dns-collector/blob/c550ac066a3d2e820b44a7af666362178fe9284f/dnsutils/message.go#L159
https://github.com/dmachard/go-dns-collector/blob/c550ac066a3d2e820b44a7af666362178fe9284f/transformers/normalize.go#L84

**Comment by gallypette** [comment]
I will give it a shot

**Comment by gallypette** [comment]
It required a bit more editing :)

**Review by dmachard — APPROVED** [review]

**Comment by dmachard** [comment]
look good to me, thanks

**Comment by dmachard** [comment]
It's possible for you to make a new pull request to make the `response_payload`  directive more generic ? 
In fact the name is not appropriate because the DNS payload can also contains a query.

**Comment by gallypette** [comment]
good point. Would `dns_payload` be ok?

**Comment by dmachard** [comment]
I think so. 

I missed that in my first review, sorry for that.

**Pull request merged**
